# Generated by Django 3.0.5 on 2020-04-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
