# Generated by Django 3.0.5 on 2020-04-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_session_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('name', 'session')},
        ),
    ]
