# Generated by Django 3.0.5 on 2020-04-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0003_auto_20200418_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='submitted_prompts',
            field=models.BooleanField(default=False),
        ),
    ]
