# Generated by Django 3.0.5 on 2020-04-19 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0004_player_submitted_prompts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='question',
        ),
        migrations.AddField(
            model_name='prompt',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jokes.Player'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jokes.Session'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
