# Generated by Django 3.0.5 on 2020-05-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0005_auto_20200419_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(default='start', max_length=80),
            preserve_default=False,
        ),
    ]
